import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, BriefcaseBusiness, CheckCircle2, FileText, MapPin, Search, Upload, X } from "lucide-react";
import { useNavigate,useSearchParams } from "react-router-dom";
import api from "../services/api";
import "./Jobs.css";

const money=(a,b)=>a&&b?`₹${Number(a).toLocaleString("en-IN")} - ₹${Number(b).toLocaleString("en-IN")}`:"Salary not disclosed";
export default function Jobs(){
 const navigate=useNavigate(); const [params]=useSearchParams();const [jobs,setJobs]=useState([]);const [skills,setSkills]=useState([]);const [search,setSearch]=useState("");const [location,setLocation]=useState("");const [type,setType]=useState("");const [skill,setSkill]=useState("");const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(null);const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem("hireflow_saved_jobs")||"[]"));const [message,setMessage]=useState("");
 const load=async()=>{try{setLoading(true);const r=await api.get("/jobs/list/",{params:{search,location,job_type:type,skill,page:1,page_size:20}});setJobs(r.data.jobs||[])}catch(e){setMessage(e.response?.data?.message||"Could not load jobs.")}finally{setLoading(false)}};
 useEffect(()=>{api.get("/skills/").then(r=>setSkills(r.data.skills||[])).catch(()=>{})},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,location,type,skill]);
 useEffect(()=>{const id=Number(params.get("apply")); if(id && jobs.length){const match=jobs.find(j=>j.id===id); if(match)setSelected(match)}},[params,jobs]);
 const toggle=id=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem("hireflow_saved_jobs",JSON.stringify(next))};
 return <div className="portal-page"><header className="portal-header"><button className="back-button" onClick={()=>navigate("/dashboard")}><ArrowLeft size={17}/> Dashboard</button><div className="portal-title"><span>JOB MARKETPLACE</span><h1>Find your next opportunity</h1><p>Search open positions published through HireFlow.</p></div></header>
 <main className="jobs-page-content"><section className="filters"><div className="filter-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, company or skill"/></div><div className="filter-row"><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location"/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All job types</option><option value="full-time">Full-time</option><option value="part-time">Part-time</option><option value="internship">Internship</option><option value="remote">Remote</option></select><select value={skill} onChange={e=>setSkill(e.target.value)}><option value="">All skills</option>{skills.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select></div></section>
 {message&&<div className="jobs-alert">{message}</div>}{loading?<div className="page-loading">Loading open positions...</div>:<div className="jobs-results">{jobs.map(job=><article className="market-job" key={job.id}><div className="market-logo">{job.title.slice(0,1).toUpperCase()}</div><div className="market-info"><div className="market-title"><h2>{job.title}</h2><CheckCircle2 size={16}/></div><strong>{job.posted_by}</strong><div className="market-meta"><span><MapPin size={13}/>{job.location}</span><span><BriefcaseBusiness size={13}/>{job.job_type}</span><span>{money(job.salary_min,job.salary_max)}</span></div><p>{job.description}</p><div className="market-tags">{(job.skills||[]).map(s=><span key={s.id}>{s.name}</span>)}</div></div><div className="market-actions"><button className={saved.includes(job.id)?"saved-btn":"save-btn"} onClick={()=>toggle(job.id)}><Bookmark size={15} fill={saved.includes(job.id)?"currentColor":"none"}/>{saved.includes(job.id)?"Saved":"Save"}</button><button className="market-apply" onClick={()=>setSelected(job)}>Apply Now <ArrowRight size={15}/></button></div></article>)}{!jobs.length&&<div className="empty-jobs"><BriefcaseBusiness size={32}/><h2>No open jobs found</h2><p>Try changing your search or filters.</p></div>}</div>}
 </main>{selected&&<ApplyModal job={selected} close={()=>setSelected(null)} done={()=>{setSelected(null);setMessage("Application submitted successfully.")}}/>}</div>;
}
function ApplyModal({job,close,done}){const [resume,setResume]=useState(null);const [cover,setCover]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const submit=async e=>{e.preventDefault();if(!resume){setError("Please attach your resume (PDF, DOC or DOCX, max 5 MB).");return}try{setLoading(true);const fd=new FormData();fd.append("resume",resume);fd.append("cover_letter",cover);await api.post(`/jobs/${job.id}/apply/`,fd);done()}catch(e){setError(e.response?.data?.message||"Application could not be submitted.")}finally{setLoading(false)}};return <div className="modal-backdrop"><div className="apply-modal"><button className="modal-close" onClick={close}><X/></button><span className="portal-kicker">APPLICATION</span><h2>{job.title}</h2><p>{job.posted_by} · {job.location}</p><form onSubmit={submit}><label>Resume<input type="file" accept=".pdf,.doc,.docx" onChange={e=>setResume(e.target.files?.[0]||null)}/><small><Upload size={14}/> {resume?resume.name:"PDF, DOC or DOCX · max 5 MB"}</small></label><label>Cover letter <span>(optional)</span><textarea value={cover} onChange={e=>setCover(e.target.value)} rows="6" placeholder="Tell the recruiter briefly why you are a strong fit..."/></label>{error&&<div className="modal-error">{error}</div>}<button className="modal-submit" disabled={loading}>{loading?"Submitting...":<>Submit Application <ArrowRight size={16}/></>}</button></form></div></div>}
