import { useEffect, useState } from "react";
import { ArrowLeft, FileText, Mail, Search, UserRound, X } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import api from "../services/api";
import RecruiterLayout from "./RecruiterLayout";
import "./RecruiterApplicants.css";

const labels={applied:"Applied",shortlisted:"Shortlisted",rejected:"Rejected",hired:"Hired"};
export default function RecruiterApplicants(){
 const {id}=useParams(); const [job,setJob]=useState(null); const [apps,setApps]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [selected,setSelected]=useState(null); const [saving,setSaving]=useState(null);
 useEffect(()=>{Promise.all([api.get(`/jobs/${id}/`),api.get(`/jobs/${id}/applicants/`)]).then(([j,a])=>{setJob(j.data.job);setApps(a.data.applicants||[])}).catch(e=>setError(e.response?.data?.message||"Unable to load applicants.")).finally(()=>setLoading(false))},[id]);
 const updateStatus=async(applicationId,status)=>{setSaving(applicationId);try{await api.patch(`/applications/${applicationId}/status/`,{status});setApps(v=>v.map(a=>a.application_id===applicationId?{...a,status}:a));if(selected?.application_id===applicationId)setSelected(v=>({...v,status}));}catch(e){alert(e.response?.data?.message||"Unable to update status.")}finally{setSaving(null)}};
 const filtered=apps.filter(a=>`${a.candidate.username} ${a.candidate.email}`.toLowerCase().includes(search.toLowerCase()));
 return <RecruiterLayout title="Applicants" subtitle={job?`${job.title} · ${job.location}`:"Review candidates for this opening."}>
  {loading?<div className="recruiter-loading">Loading applicants…</div>:error?<div className="recruiter-error">{error}</div>:<>
   <div className="applicant-top"><Link to="/recruiter/jobs" className="back-link"><ArrowLeft size={16}/> Back to jobs</Link><div className="applicant-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search candidates…"/></div></div>
   <div className="pipeline"><div><strong>{apps.length}</strong><span>Total applicants</span></div><div><strong>{apps.filter(a=>a.status==="shortlisted").length}</strong><span>Shortlisted</span></div><div><strong>{apps.filter(a=>a.status==="hired").length}</strong><span>Hired</span></div><div><strong>{apps.filter(a=>a.status==="rejected").length}</strong><span>Rejected</span></div></div>
   {filtered.length===0?<div className="jobs-empty"><UserRound size={28}/><h3>No applicants found</h3><p>{apps.length?"Try another search.":"No one has applied to this job yet."}</p></div>:<div className="applicant-list">{filtered.map(a=><div className="applicant-card" key={a.application_id}><div className="candidate-avatar">{a.candidate.username.slice(0,1).toUpperCase()}</div><div className="candidate-main"><div className="candidate-name-row"><strong>{a.candidate.username}</strong><span className={`application-status ${a.status}`}>{labels[a.status]||a.status}</span></div><div className="candidate-contact"><span><Mail size={13}/>{a.candidate.email}</span><span>Applied {new Date(a.applied_at).toLocaleDateString()}</span></div><div className="candidate-actions"><button onClick={()=>setSelected(a)}><FileText size={14}/> View application</button>{a.resume&&<a href={`${import.meta.env.VITE_API_URL?.replace(/\/api\/?$/,"")||"http://localhost:8000"}${a.resume}`} target="_blank" rel="noreferrer"><FileText size={14}/> Resume</a>}<select value={a.status} disabled={saving===a.application_id} onChange={e=>updateStatus(a.application_id,e.target.value)}><option value="applied">Applied</option><option value="shortlisted">Shortlisted</option><option value="rejected">Rejected</option><option value="hired">Hired</option></select></div></div></div>)}</div>}
  </>}
  {selected&&<div className="app-modal-backdrop" onClick={()=>setSelected(null)}><div className="app-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X size={17}/></button><div className="modal-avatar">{selected.candidate.username.slice(0,1).toUpperCase()}</div><h3>{selected.candidate.username}</h3><p className="modal-email">{selected.candidate.email}</p><div className="modal-status"><span>Status</span><strong className={`application-status ${selected.status}`}>{labels[selected.status]}</strong></div><div className="cover-letter"><span>Cover letter</span><p>{selected.cover_letter||"No cover letter was provided."}</p></div><div className="modal-footer"><button className="secondary-modal" onClick={()=>setSelected(null)}>Close</button>{selected.resume&&<a className="primary-modal" href={`${import.meta.env.VITE_API_URL?.replace(/\/api\/?$/,"")||"http://localhost:8000"}${selected.resume}`} target="_blank" rel="noreferrer">Open resume</a>}</div></div></div>}
 </RecruiterLayout>
}
