# Generated by Django 5.2.7 on 2025-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productmodelclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelclass',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
    ]
