# Generated by Django 5.2.7 on 2025-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productmodelclass_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productmodelclass',
            name='image',
            field=models.FileField(upload_to='upload/products'),
        ),
    ]
