# Generated by Django 5.2.7 on 2025-12-25 21:42

from django.db import migrations


def fix_image_paths(apps, schema_editor):
    ProductModelClass = apps.get_model('store', 'ProductModelClass')
    for product in ProductModelClass.objects.all():
        if product.image and product.image.name.startswith('upload/'):
            product.image.name = product.image.name.replace('upload/', '', 1)
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_usermodelclass_alter_productmodelclass_image'),
    ]

    operations = [
        migrations.RunPython(fix_image_paths),
    ]
