# Generated by Django 5.2.7 on 2025-12-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_fix_image_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelclass',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
        migrations.CreateModel(
            name='cartModelClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.productmodelclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usermodelclass')),
            ],
        ),
    ]
