# Generated by Django 5.2.7 on 2025-12-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productmodelclass_image_cartmodelclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModelClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalprice', models.IntegerField()),
                ('orderdate', models.DateField(auto_now=True)),
                ('paymentmethod', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('orderstatus', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.productmodelclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usermodelclass')),
            ],
        ),
    ]
