# Generated by Django 5.2.7 on 2026-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('price', models.TextField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
