# Generated by Django 5.2.7 on 2026-01-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categorymodelclass_productmodelclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelclass',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productmodelclass',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
