# Generated by Django 6.0.1 on 2026-01-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_categorymodelclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
